"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var express_1 = require("express");
var auth_js_1 = require("./routes/auth.js");
var producer_js_1 = require("./producer.js");
var cors_1 = require("cors");
var app = (0, express_1.default)();
app.use((0, cors_1.default)());
app.use(express_1.default.json());
(0, producer_js_1.connectKafka)();
app.use("/api/auth", auth_js_1.default);
exports.default = app;
